[project]
name = "ZenUI"
version = "0.1.0"
description = "A UI component library based on QWidget in PySide6"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.3.2",
    "pyside6>=6.9.1",
    "pywin32>=311",
]
